name: Build

on:
  pull_request:
    branches: 
     - dev
     - main

jobs:

  build:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout Repository
      uses: actions/checkout@master
    - name: Install routres package
      run: composer require laravel/ui 
    - name: Install Packages
      run: composer install --no-dev
