name: Build

on:
  pull_request:
    branches: 
     - dev
     - main

jobs:

  build:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout Repository
      uses: actions/checkout@master
    # - name: Install routres package
      # run: composer require laravel/ui -W
    - name: Install Packages
      run: |
        composer dump-autoload
        compsoser
        composer update --ignore-platform-reqs
      # run: composer install --ignore-platform-reqs
      # run: composer install --no-dev -W
