name: Laravel CI

on:
  [push]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: smoelenboek
          MYSQL_USER: root
          MYSQL_PASSWORD: ''
          MYSQL_ROOT_PASSWORD: ''
        ports:
          - 3306
          
    steps:
    - uses: actions/checkout@v2
    
    - name: Verify MySQL connection
      run: |
        mysql --version
        sudo apt-get install -y mysql-client
        mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uuser -psecret -e "SHOW DATABASES"
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.github', '.env');"

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
