name: Test

on:
  [push]

jobs:

  build:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: Install required files
      run: composer install --no-scripts, composer require laravel/ui, php artisan optimize
    - name: Migrate Database & Execute Tests
      run: php artisan migrate:fresh --seed
    - name: Run tests
      run: php artisan test
